name: DragonicRoyale
version: 1.0.0
main: main.java.com.drgnfireyellow.dragonicroyale.DragonicRoyale
description: A simple battle royale plugin
author: DrgnFireYellow
website: https://github.com/drgnfireyellow
api-version: '1.20'

commands:
  'battleroyale':
    description: 'Join the battle royale lobby'
  'startbattleroyale':
    description: 'Start your battle royale lobby (Only if host)'